name: FastAPI CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest  # Assuming you have test files

      - name: Build Docker image
        run: |
          docker build -t fastapi-weather-app .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag fastapi-weather-app your-dockerhub-username/fastapi-weather-app:latest
          docker push gangadhars24/fastapi-weather-app:latest

      - name: Deploy to AKS
        run: |
          az aks get-credentials --resource-group yourResourceGroup --name yourAKSCluster
          kubectl apply -f k8s-deployment.yml
